spring:
  application:
    name: code_link

  datasource:
    url: jdbc:mysql://localhost:3306/codelink
    username: xxxxx
    password: xxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 5765
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0